# Generated by Django 6.0.7 on 2026-07-30 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'administrateur'), ('TEACHERS', 'enseignant'), ('STUDENTS', 'etudiant')], max_length=25),
        ),
    ]
