# Generated by Django 6.0.7 on 2026-07-31 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_alter_utilisateur_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='role',
            field=models.CharField(choices=[('admin', 'administrateur'), ('enseignant', 'enseignant'), ('etudiant', 'etudiant')], max_length=25),
        ),
    ]
