# Generated by Django 6.0.7 on 2026-08-03 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_alter_utilisateur_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='role',
            field=models.CharField(choices=[('admin', 'administrateur'), ('enseignant', 'enseignant'), ('etudiant', 'etudiant')], default='etudiant', max_length=25),
        ),
    ]
