# Generated by Django 6.0.7 on 2026-07-31 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new_project', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enseignant',
            name='contact',
        ),
    ]
