# Generated by Django 6.0.7 on 2026-08-03 10:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_project', '0002_remove_enseignant_contact'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Matieres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='matiere',
            name='enseignant',
        ),
        migrations.RemoveField(
            model_name='notes',
            name='matiere',
        ),
        migrations.RemoveField(
            model_name='notes',
            name='etudiant',
        ),
        migrations.AlterModelOptions(
            name='etudiant',
            options={},
        ),
        migrations.RemoveField(
            model_name='etudiant',
            name='date_naissance',
        ),
        migrations.RemoveField(
            model_name='etudiant',
            name='sexe',
        ),
        migrations.AddField(
            model_name='etudiant',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='etudiant',
            name='id_user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='etudiant', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='matricule',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='classe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='new_project.classes'),
        ),
        migrations.CreateModel(
            name='Professeur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('age', models.IntegerField(default=0)),
                ('classe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='new_project.classes')),
                ('id_user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='professeur', to=settings.AUTH_USER_MODEL)),
                ('matiere', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='new_project.matieres')),
            ],
        ),
        migrations.DeleteModel(
            name='Enseignant',
        ),
        migrations.DeleteModel(
            name='Matiere',
        ),
        migrations.DeleteModel(
            name='Notes',
        ),
        migrations.DeleteModel(
            name='Classse',
        ),
    ]
