# Generated by Django 6.0.7 on 2026-08-03 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new_project', '0003_classes_matieres_remove_matiere_enseignant_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='etudiant',
            options={'verbose_name': 'Etudiant', 'verbose_name_plural': 'Etudiants'},
        ),
        migrations.AlterModelOptions(
            name='matieres',
            options={'verbose_name': 'Matière', 'verbose_name_plural': 'Matières'},
        ),
        migrations.AlterModelOptions(
            name='professeur',
            options={'verbose_name': 'Professeur', 'verbose_name_plural': 'Professeurs'},
        ),
    ]
