# Generated by Django 6.0.7 on 2026-08-03 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new_project', '0004_alter_etudiant_options_alter_matieres_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classes',
            options={'verbose_name': 'Classe', 'verbose_name_plural': 'Classes'},
        ),
    ]
