# Generated by Django 6.0.7 on 2026-08-21 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_project', '0007_notes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notes',
            options={'verbose_name': 'Absence', 'verbose_name_plural': 'Absences'},
        ),
        migrations.CreateModel(
            name='Absences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absences', to='new_project.etudiant')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absences', to='new_project.matieres')),
                ('professeur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='new_project.professeur')),
            ],
        ),
    ]
