# Generated by Django 6.0.7 on 2026-08-21 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new_project', '0008_alter_notes_options_absences'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Absences',
            new_name='Absence',
        ),
    ]
