# Generated by Django 6.0.7 on 2026-08-21 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new_project', '0009_rename_absences_absence'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='matieres',
            options={'verbose_name': 'Matière', 'verbose_name_plural': 'Matieres'},
        ),
    ]
