# Generated by Django 6.0.7 on 2026-08-27 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new_project', '0010_alter_matieres_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='absence',
            options={'verbose_name': 'Absence', 'verbose_name_plural': 'Absences'},
        ),
        migrations.AlterModelOptions(
            name='notes',
            options={'verbose_name': 'Note', 'verbose_name_plural': 'Notes'},
        ),
    ]
